# Numpy Array

In [1]:
import numpy as np

In [2]:
l=[1,2,3]

In [3]:
arr = np.array(l)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [5]:
arr = np.array(my_mat)

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
np.linspace(0,10,5) #st, end, number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.eye(3) # 2D identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(2,3)

array([[0.44363978, 0.88624025, 0.09631545],
       [0.05477966, 0.65827184, 0.8475666 ]])

In [27]:
np.random.randint(1,100,4)

array([68, 22, 61, 69], dtype=int32)

In [36]:
arr = np.random.rand(1,20)
arr

array([[0.2595304 , 0.2901873 , 0.90475161, 0.89882341, 0.59764926,
        0.39638536, 0.87564553, 0.20349001, 0.75373711, 0.98639106,
        0.03516652, 0.90510218, 0.51925903, 0.33434249, 0.02632164,
        0.23673131, 0.87397536, 0.50169743, 0.32274543, 0.81679626]])

In [37]:
arr.reshape(5,4)

array([[0.2595304 , 0.2901873 , 0.90475161, 0.89882341],
       [0.59764926, 0.39638536, 0.87564553, 0.20349001],
       [0.75373711, 0.98639106, 0.03516652, 0.90510218],
       [0.51925903, 0.33434249, 0.02632164, 0.23673131],
       [0.87397536, 0.50169743, 0.32274543, 0.81679626]])

In [38]:
arr.reshape(10,2)

array([[0.2595304 , 0.2901873 ],
       [0.90475161, 0.89882341],
       [0.59764926, 0.39638536],
       [0.87564553, 0.20349001],
       [0.75373711, 0.98639106],
       [0.03516652, 0.90510218],
       [0.51925903, 0.33434249],
       [0.02632164, 0.23673131],
       [0.87397536, 0.50169743],
       [0.32274543, 0.81679626]])

In [39]:
arr.max()

np.float64(0.9863910636602046)

In [40]:
arr.min()

np.float64(0.026321644369127095)

In [42]:
arr.argmax() #location

np.int64(9)

In [43]:
arr.dtype

dtype('float64')

## numpy indexing and selection

In [44]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[3]

np.int64(3)

In [46]:
arr[1:3]

array([1, 2])

In [47]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[1:3] = 100

In [49]:
arr

array([  0, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [54]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr[1][2]

np.int64(6)

In [56]:
arr[1,2]

np.int64(6)

In [57]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [63]:
arr[[1,2,]]

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[arr > 5] 

array([ 6,  7,  8,  9, 10])

In [68]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])